###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

# Name of website
title: Portfolio Project

# Your name to show in the footer
author: Kira

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

permalink: pretty

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
